spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/classifier_service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: note
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080